-- Applied by `pnpm db:migrate`, which wraps this in a transaction and records
-- the version. Also runnable on its own: psql -1 -f db/migrations/001_initial.sql
--
-- Written as plain SQL rather than generated by an ORM: the schema is part of
-- what this project is judged on, and an ORM would put a layer between what is
-- read and what actually runs.

-- --------------------------------------------------------------------------
-- users
-- --------------------------------------------------------------------------

CREATE TABLE users (
  id         BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name       TEXT        NOT NULL CHECK (btrim(name) <> ''),
  last_name  TEXT        NOT NULL CHECK (btrim(last_name) <> ''),
  email      TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Addresses differ only by case are the same address. A unique index on
-- lower(email) rather than the citext extension: CREATE EXTENSION needs a
-- privilege the application's role deliberately does not have, and an
-- expression index needs nothing.
CREATE UNIQUE INDEX users_email_lower_key ON users (lower(email));

-- --------------------------------------------------------------------------
-- tasks
-- --------------------------------------------------------------------------

CREATE TYPE task_status AS ENUM ('open', 'archived');

CREATE TABLE tasks (
  id          BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title       TEXT        NOT NULL CHECK (btrim(title) <> ''),
  description TEXT,
  status      task_status NOT NULL DEFAULT 'open',
  archived_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- A task is archived exactly when it has an archive time. Stating it here
  -- means no code path can leave the two disagreeing.
  CONSTRAINT archived_at_matches_status
    CHECK ((status = 'archived') = (archived_at IS NOT NULL))
);

CREATE INDEX tasks_status_idx ON tasks (status);

-- --------------------------------------------------------------------------
-- task_assignments
-- --------------------------------------------------------------------------

-- One row per person per task. The composite primary key is what makes
-- assigning the same user twice impossible rather than merely discouraged:
-- POST /tasks/:id/assign can insert blindly and let the key decide.
CREATE TABLE task_assignments (
  task_id      BIGINT      NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
  user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  assigned_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  PRIMARY KEY (task_id, user_id)
);

-- The primary key already serves lookups by task. This one serves
-- GET /users/:id/tasks, which reads the other way round.
CREATE INDEX task_assignments_user_id_idx ON task_assignments (user_id);

-- --------------------------------------------------------------------------
-- notification_attempts
-- --------------------------------------------------------------------------

-- Every attempt to notify the client system that a task was archived, whether
-- it succeeded or not. Read back by GET /tasks/:id/notifications.
CREATE TABLE notification_attempts (
  id             BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id        BIGINT      NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
  attempt_number INT         NOT NULL CHECK (attempt_number BETWEEN 1 AND 3),
  attempted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Null when the destination never answered: a timeout has no status code.
  http_status    INT,
  error          TEXT,

  -- Three attempts at most, each recorded once. If a retry loop ever ran twice
  -- for the same task this constraint is what says so, instead of the table
  -- quietly growing.
  UNIQUE (task_id, attempt_number)
);

CREATE INDEX notification_attempts_task_id_idx ON notification_attempts (task_id);

-- --------------------------------------------------------------------------
-- idempotency_keys
-- --------------------------------------------------------------------------

CREATE TYPE idempotency_state AS ENUM ('in_progress', 'completed');

-- One row per (key, endpoint). The row is claimed before the work runs, which
-- is what lets a second request arriving in parallel block on it rather than
-- perform the operation a second time.
--
-- request_hash exists so the same key sent with a different body is refused
-- instead of silently replaying an answer to a question nobody asked.
CREATE TABLE idempotency_keys (
  key             TEXT              NOT NULL,
  endpoint        TEXT              NOT NULL,
  request_hash    TEXT              NOT NULL,
  state           idempotency_state NOT NULL DEFAULT 'in_progress',
  response_status INT,
  response_body   JSONB,
  created_at      TIMESTAMPTZ       NOT NULL DEFAULT now(),
  PRIMARY KEY (key, endpoint),

  CONSTRAINT completed_rows_carry_a_response
    CHECK (state = 'in_progress'
           OR (response_status IS NOT NULL AND response_body IS NOT NULL))
);
